@extends('layouts.app')

@section('content')
@section('background','/img/privacy.png')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Privacy Policy</div>

                <div class="panel-body">
                  Terms of Service
  Thank you for your interest in Fast Foodie, and the requisition for your mobile device (the "Website") distributed to you by Fast Foodie LLC. ("Fast Foodie" "us" or "we"), and our web site at FastFooodie.com (the "Site"), also including, as well as related web sites, networks, downloadable software, and other services exhibited by us. The link to this Terms of service is presented (united, jointly with the App and Site, our "service"). These Terms of Service (these "Terms"), including the Privacy Policy integrated into these Terms by mentioning, and any other applicable systems and guidelines of principle. It will be interchanged from time to time, the conduct of policy will change your use of the service. These Terms compose of a legal agreement between you and Fast Foodie. In order to use the service of Fast Foodie, you must agree to these Terms.
  The Terms that are provided with limited contemplation, are all disputes between you and Fast Foodie, will arise out of or relating to these Terms or your use of the service will be resolved by ‘Binding Arbitrament’. YOU AGREE TO GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend your rights under these Terms, except for matters covered by Section 17.3 of these Terms. Your rights will be determined by a ‘Impartial Arbitrator’ and NOT a judge or jury, and your claims cannot be brought as a class action. Please review Section 17 (“Dispute Resolution and Arbitration”) for the details regarding your agreement to arbitrate most disputes with Fast Foodie.
  BY DOWNLOADING, INSTALLING, OR OTHERWISE ACCESSING OR USING THE SERVICE, YOU AGREE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE, YOU MAY NOT USE THE SERVICE.
  Fast Foodie provides a mobile app and web-based technology platform that connects consumers/customers, restaurants, and retail stores, with independent contractor couriers to further promote on-demand delivery services (the "ROSTRUM"). The Platform (rostrum) gives consumers/customers may request that merchandise or food, can be delivered to them from particular retail locations or restaurants. Independent contractor couriers can access the Platform (rostrum) and receive delivery opportunities. Fast Foodie is not a retail store, restaurant, food delivery service, merchandise delivery service, or food preparation entity.
  FAST FOODIE DOES NOT PROVIDE DELIVERY SERVICES. INDEPENDENT CONTRACTORS (EACH A "COURIER") OFFER DELIVERY SERVICES THROUGH USE OF THE SERVICE. FAST FOODIE OFFERS INSTRUCTIONS AND A METHOD TO OBTAIN COURIER SERVICES, BUT DOES NOT AND DOES NOT INTEND TO PROVIDE COURIER SERVICES OR ACT IN ANY WAY AS A COURIER, AND HAS NO RESPONSIBILITY OR LIABILITY FOR ANY COURIER.
  As provided in greater detail in these Terms, you agree and acknowledge these material Terms:
  The App is certified (not sold to you), and you may use the service only as set forth in these Terms;
  Your use of the service may be subject to separate third party terms of service and fees, including without limitation your mobile network operator’s ("Carrier") terms of service and fees, including fees charged for data usage and overage, which are your sole responsibility;
  You consent to the collection, sharing, and use of your personally identifiable information in accordance with Fast Foodie Privacy Policy.
  The service is provided "as is" without warranties of any kind, and Fast Foodie’ accountability to you is limited
  Controversy arising under these Terms will be resolved by ‘Binding Arbitrament’.
  BY ACCEPTING THESE TERMS, YOU AND FAST FOODIE ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION. YOU AGREE TO WAIVE YOUR RIGHT TO GO TO COURT to assert or defend your rights under this contract (except for matters that may be taken to small claims court). Your rights will be determined by a UNBIASED ARBITRATOR and NOT a judge or jury, and your claims cannot be brought as a class action. Please review the Dispute Resolution and Arbitration section below for the details regarding your agreement to arbitrate any disputes with FAST FOODIE.

  Account Access
  The Age of Consent to use Fast Foodie is at least eighteen (18) years old to use the service. By agreeing to these Terms, you represent and warrant to us (Fast Foodie):
  You are at least eighteen (18) years old;
  You have not previously been suspended, denied or removed from the service
  Your registration and your use of the service is in compliance with any and all applicable laws and regulations.
  If you are using the service on behalf of an entity, organization, or company, you represent and warrant that you have the authority to bind that organization to these Terms and you agree to be bound by these Terms on behalf of that organization, company, and entity.

  Accounts & Registration
  To access some features of the service, you must register for an account. When you register for an account, you may be required to provide us with some information about yourself (such as your name, credit card information, e-mail address, phone number or other contact information). You must agree that the information you provide to us is accurate (factual), and that you will keep it up-to-date, and current at all times. When you register, you will be asked to provide a password. You are solely responsible for maintaining the confidentiality of your account and password. Also, any password for Facebook, Google, or any other third party login. You accept responsibility for all activities that occur under your account. If you have reason to believe that your account is no longer secure, you must immediately notify us via our Help Center.

  Scope of License
  The App/Website is licensed, not sold, to you for use only under the terms of this license. Fast Foodie reserves all rights not expressly granted to you. Subject to your complete and ongoing compliance with these Terms. Fast Foodie hereby grants you a personal, sparse, annulled, non-transferable license to use the App/Website on compatible devices that you own or control, solely for your non-commercial use.
  You may not change (modify), alter, reproduce, distribute or make the App available over a network where it could be used by multiple devices at the same time. You may not rent, lease, lend, sell, redistribute or sublicense the App. If you breach these license restrictions, or otherwise exceed the scope of the license granted in these Terms, you may be subject to prosecution and legal damages, as well as liability for infringement of intellectual property rights. These Terms will govern any updates provided to you by Fast Foodie that replace and/or supplement the original App. Otherwise, the upgrade is accompanied by a separate license in which case the terms of that license will govern.

  Payment Terms
  4.A - General Payment Terms
  Pertaining to certain features of the service, including the placing of orders/accepting orders using the service, may require you to pay fees. Before you pay any fees, you will have an opportunity to review and accept an approximation of the fees that you will be charged. Please visit our Help Center for information on how we figure the fee estimate. All fees are in U.S. Dollars and are non-refundable. This no refund policy applies at all times regardless of your decision to terminate your usage. The decision to discontinue your usage and any distort caused to our service for any reason whatsoever.
  Fast Foodie, at its sole carefulness, may offer credits or refunds on a case-by-case basis. Any credit and/or refund requests must be made within Twenty-Four (24) hours after the delivery was completed. Fast Foodie may change the delivery or other fees for any feature of the service, including by adding fees, on a going-forward basis at any time now or in the near future.
  Fast Foodie will charge the payment method you specify at the time of purchase or as otherwise specified by you in your account information. Fast Foodie reserves the right to determine final reign pricing. Please be advised that the pricing information published on the App/Website may not reflect the reign pricing.) Fast Foodie, at its sole discretion, may make promotional offers with different features and different rates to any of our customers/members. These promotional offers, unless made to you, shall have no bearing whatsoever on your offer or contract. We may change the fees for the service at any time as we seem necessary for our business. We encourage you to check our website periodically to learn more about how we charge for the service.
  4.B - Authorization
  You are giving permission to Fast Foodie to charge all sums for orders that you make and services you select to the payment method specified in your account. When you order on Fast Foodie, a temporary pre-validation hold is placed on your payment card to verify that the card is valid and there is credit available for your proposed purchase. Once your order is complete, you will be charged the final order total and the pre-validation hold will be lifted within 24-72 business hours depending on your bank. The pre-validation hold remains even if an order is canceled by a customer or by Fast Foodie, and may remain on your card for up to 5 business days.
  Fast Foodie also places an initial temporary pre-authorization hold on each new payment method you add to your account.
  4.C - Delinquent Accounts
  If payment for purchases on your account is delinquent or late, your account information may be sent to a collection agency / debt collector. You may be subject to a collection action, and payment of collection related fees and costs. If you have questions regarding an outstanding balance on your account, please contact us via our Help Center.
  4.D – Customer Not Available
  Fast Foodie reserves the right to charge a customer the full order amount if that customer is not at the designated delivery location when the courier arrives to complete the delivery order.
  4.E – Cancelled Orders
  Cancelling your Fast Foodie order, you may be charged depending on what stage the order was in when you cancelled it. If you cancel a delivery after it has been accepted but is not yet being prepared by the merchant, you will not be charged a cancellation fee. If you cancel a delivery after a merchant has started preparing your order, you will be charged the price of the items, including applicable taxes, plus a cancellation fee of up to $5. If you cancel a delivery after it is out for delivery, you will be charged the full price of the order.
  4.F – Returned Items
  If an item has to be returned for any reason, you may be subject to a non-refundable $10 return/restocking fee. For alcoholic items (Legal Age Consenting Items), the courier reserves the right to refuse delivery and return the item(s) if the name on your ID does not match the name on your order. You will be denied alcoholic items (Legal Age Consenting Items), if you are not at least twenty-one (21) years old ("Legal Age"), if you cannot provide valid government-issued photo ID that you are Legal Age, or if you are visibly intoxicated.
  5. Third-Party Relations
  5.A – Third-Party Distributers
  Throughout the use of the service, you may purchase goods and services from third-party merchants through the service. Any such activity, and any disputes, terms, conditions, warranties or representations associated with that activity, is solely between you and the applicable third party. Fast Foodie and its licensors shall have no liability, legalities, obligation or responsibility for any purchase or transaction between you and any third-party provider. In no event shall Fast Foodie or its licensors be held accountable for any content, products, services or other materials on or available from third-party sites or third-party providers. Certain third-party providers of goods and/or services may require your approval to additional or different terms and conditions prior to your use of or access to such goods or services. Fast Foodie repudiates any and all responsibility or liability arising from such agreements between you and a third party.
  5.B - Couriers
  You may engage third-party Couriers through the Service to provide delivery services to you and may interact with those Couriers. Any interactions or discrepancies between you and a Courier are solely between you and that Courier. Fast Foodie and its licensors shall have no liability, obligation or responsibility for any interaction between you and any Courier.
  5.C – Third-Party Advertising
  The service could contain third-party advertising and marketing. By you agreeing to these Terms you agree to receive such advertising and marketing.
  5.D – Links To Third Party Sites
  The service could contain links to third-party websites. Linked websites are not under our control, and we are not responsible for their content.
  6. Your Use Of The Service
  In order to use the Service, you must agree to the following:
  The service, including any content that forms part of the Service, contains proprietary content, information and material that is protected by applicable intellectual property and other laws, including copyright;
  You will not violate, or encourage others to violate, any right of a third party, including by infringing or misappropriating any third-party intellectual property right, or otherwise engage in the unauthorized use of any proprietary content, information or materials;
  Unless expressly permitted, you may not alter, modify, create derivative works of, sell, license or in any way exploit any part of the Service, and you agree not to copy, reproduce, distribute, publish, display, perform, transmit, stream or broadcast any part of the Service without prior written authorization;
  You agree not to bypass any security or other features of the Service designed to control the manner in which the Service is used, harvest or mine content from the Service, or otherwise access or use the Service in a manner inconsistent with individual human use;
  You agree not to perform any fraudulent activity, including impersonating any person or entity, or accessing any other Service account without permission;
  You agree not to decipher, reverse engineer, decompile or disassemble the Service, or the software used to provide the Service, in whole or in part, or authorize, direct, or cause a third party to do so;
  You agree not to use, display, mirror, frame or utilize framing techniques to enclose the Service, or any portion thereof, unless and solely to the extent Fast Foodie makes available the means for embedding any part of the Service;
  You agree not to access, tamper with, or use non-public areas of the Service, Fast Foodie’ (and its hosting company’s) computer systems and infrastructure, or the technical delivery systems of Fast Foodie’ providers;
  You agree not to use any robot, spambot, spider, crawler, scraper or other automated means or interface not provided by us to access the Service or to extract data;
  You agree not to use the Service in any manner to harass, abuse, stalk, threaten, defame or otherwise infringe or violate the rights of any other party, and that Fast Foodie is not in any way responsible for any such use by you, nor for any harassing, threatening, defamatory, offensive or illegal messages or transmissions that you may receive as a result of using the Service;
  You agree that your use of the App may incur third-party fees, such as fees charged by your Carrier for data usage, and may be subject to third-party terms, such as your Carrier’s terms of service, and you agree to pay all such fees and abide by all such terms;
  You agree not to introduce viruses, time-bombs, worms, cancelbots, trojan horses and/or other harmful code into the Service;
  Alcoholic beverages (including but not limited to beer, wine, cider, and spirits, as applicable; all referred to as "Alcoholic Beverages") may only be purchased by individuals, including without limitation Customers, who are Legal Age. If you are a Customer, you expressly represent and warrant that: (i) you are of Legal Age; and (ii) you will provide bona fide government-issued photo identification to your courier upon delivery to you. Valid forms of identification include but are not limited to: (i) a valid motor vehicle operator’s license, (ii) a passport issued by the U.S. or by a foreign government, or (iii) a valid identification card issued to a member of the Armed Forces that includes a date of birth and a picture, showing your Legal Age. Deliveries of Alcoholic Beverages may not be made to anyone who is intoxicated, regardless of his or her age. You further understand and acknowledge that neither Fast Foodie nor the courier can accept your order of Alcoholic Beverages, and the order will only be delivered if the third-party merchant accepts your order; and
  You agree not to do any of the acts described in this Section 6, or to assist or permit any person in engaging in any of the acts described in this Section 6.
  7. Consent To Use Of Data
  Please see Fast Foodie’ Private Policy, for more information regarding information Fast Foodie collects, and how it uses and shares that information.
  8. Intellectual Property Ownership
  The Service, and the media and materials contained in the Service, including all intellectual property rights in the Service, are the sole and exclusive property of Fast Foodie and its licensors. Except for the limited license expressly granted by and to you under these Terms, no other rights, licenses, or immunities are granted or shall be deemed to be granted under these Terms, either expressly, or by implication, estoppel or otherwise. All rights not expressly granted by Fast Foodie in these Terms are expressly reserved.
  9. FeedBack
  You may choose to, or Fast Foodie may invite you to, submit comments, bug reports, ideas or other feedback about the Service ("Feedback"). By submitting Feedback, you agree that Fast Foodie is free to use such Feedback at its discretion without any obligation to you. Fast Foodie may also choose to disclose Feedback to third parties. You hereby grant Fast Foodie a royalty-free, perpetual, irrevocable, transferable, sublicensable, worldwide, nonexclusive license under all rights necessary to incorporate and use your Feedback for any purpose.
  10. Indemnity
  You are responsible for your use of the Service, and you agree to defend (at Fast Foodie’ option) and indemnify Fast Foodie and its officers, directors, employees, contractors, consultants, affiliates, investors, service providers, business partners, subsidiaries and agents from and against every claim, liability, damage, loss, and expense, including reasonable attorneys’ fees and costs, arising out of or in any way connected with:
  Your violation of any of these Terms, any representation, warranty, or agreement referenced in these Terms, or any applicable law or regulation;
  Your violation of any third-party right, including any intellectual property right or publicity, confidentiality, other property, or privacy right; or
  Any dispute or issue between you and any third party, including any Courier, restaurant or other third-party merchant
  Fast Foodie reserves the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you (without limiting your indemnification obligations) and you agree to cooperate with our defense of that claim. If the defense or settlement is assumed by you, Fast Foodie may at any time thereafter elect to take over control of the defense and settlement of the claim. You must not settle any claim without Fast Foodie’ prior written consent.

  11. Disclaimer Of Warranties
  YOUR USE OF THE SERVICE IS AT YOUR OWN SOLE RISK. THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. ALL REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD-PARTY RIGHTS, ARE HEREBY DISCLAIMED BY FAST FOODIE TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW. FAST FOODIE MAKES NO REPRESENTATION, WARRANTY, OR GUARANTY AS TO THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, AVAILABILITY, ACCURACY OR COMPLETENESS OF THE SERVICE. FAST FOODIE DOES NOT REPRESENT OR WARRANT THAT THE USE OF THE SERVICE WILL BE SECURE, TIMELY, UNINTERRUPTED OR ERROR-FREE OR WILL OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM OR DATA; THAT THE SERVICE OR ANY PRODUCTS OR MATERIALS OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS; OR THAT THE SERVICE OR THE SERVER(S) THAT MAKE THE SERVICE AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
  FAST FOODIE’ SERVICE MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS. FAST FOODIE IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH PROBLEMS.
  FAST FOODIE RELIES UPON RESTAURANTS AND OTHER THIRD-PARTY FOOD AND BEVERAGE PROVIDERS AND RETAILERS TO PROVIDE ACCURATE ALLERGEN AND DIETARY INFORMATION AND GENERAL PRODUCT SAFETY. FAST FOODIE DOES NOT REPRESENT OR WARRANT THAT THE INFORMATION ACCESSIBLE THROUGH THE SERVICE IS ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE, INCLUDING WITHOUT LIMITATION MENUS, NUTRITIONAL AND ALLERGEN INFORMATION, PHOTOS, FOOD QUALITY OR DESCRIPTIONS, PRICING, HOURS OF OPERATION, OR REVIEWS. ALL CONTENT IS PROVIDED FOR INFORMATIONAL PURPOSES ONLY. THE RELIANCE ON ANY INFORMATION PROVIDED THROUGH THE SERVICE IS SOLELY AT YOUR OWN RISK, INCLUDING WITHOUT LIMITATION NUTRITIONAL AND ALLERGEN INFORMATION.
  FAST FOODIE DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A RESTAURANT OR OTHER THIRD PARTY THROUGH THE SERVICE OR ANY HYPERLINKED WEBSITE OR THIRD-PARTY SERVICE, AND FAST FOODIE WILL NOT BE A PARTY TO OR IN ANY WAY MONITOR ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.
  12. Limitation Of Liability
  IN NO EVENT SHALL FAST FOODIE’ AGGREGATE LIABILITY EXCEED THE FEES ACTUALLY PAID BY YOU TO FAST FOODIE IN THE THREE (3) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO SUCH CLAIM OR $100, WHICHEVER IS LESS. IN NO EVENT SHALL FAST FOODIE AND/OR ITS LICENSORS BE LIABLE TO ANYONE FOR ANY INDIRECT, PUNITIVE, SPECIAL, EXEMPLARY, INCIDENTAL, CONSEQUENTIAL OR OTHER DAMAGES OF ANY TYPE OR KIND (INCLUDING PERSONAL INJURY, LOSS OF DATA, REVENUE, PROFITS, REPUTATION, USE OR OTHER ECONOMIC ADVANTAGE) EVEN IF FAST FOODIE AND/OR ITS LICENSORS HAVE BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES
  THE SERVICE CONNECTS YOU TO COURIERS AND MERCHANTS FOR THE PURPOSES OF FACILITATING COURIER SERVICES. FAST FOODIE WILL NOT ASSESS THE SUITABILITY, LEGALITY OR ABILITY OF ANY COURIERS AND YOU EXPRESSLY WAIVE AND RELEASE FAST FOODIE FROM ANY AND ALL LIABILITY, CLAIMS OR DAMAGES ARISING FROM OR IN ANY WAY RELATED TO THE COURIERS. FAST FOODIE WILL NOT ASSESS THE QUALITY, SAFETY, OR LEGALITY OF THE ITEMS PROVIDED BY MERCHANTS OR RETAILERS ON THE PLATFORM, AND YOU EXPRESSLY WAIVE AND RELEASE FAST FOODIE FROM ANY AND ALL LIABILITY, CLAIMS OR DAMAGES ARISING FROM OR IN ANY WAY RELATED TO MERCHANTS, RETAILERS, AND THE ITEMS THEY PROVIDE. FAST FOODIE WILL NOT BE A PARTY TO DISPUTES OR NEGOTIATIONS OF DISPUTES, BETWEEN YOU AND ANY COURIERS, MERCHANTS, OR RETAILERS. RESPONSIBILITY FOR THE DECISIONS YOU MAKE REGARDING SERVICES OFFERED VIA THE SERVICE (WITH ALL THEIR IMPLICATIONS) RESTS SOLELY WITH YOU. IN ADDITION, WE WILL NOT ASSESS THE SUITABILITY, LEGALITY OR ABILITY OF ANY THIRD PARTIES AND YOU EXPRESSLY WAIVE AND RELEASE FAST FOODIE FROM ANY AND ALL LIABILITY, CLAIMS, CAUSES OF ACTION, OR DAMAGES ARISING FROM YOUR USE OF THE SERVICE, OR IN ANY WAY RELATED TO THE THIRD PARTIES INTRODUCED TO YOU BY THE SERVICE. THE QUALITY OF THE COURIER SCHEDULED THROUGH THE USE OF THE SERVICE IS ENTIRELY THE RESPONSIBILITY OF THE THIRD-PARTY COURIER WHO ULTIMATELY PROVIDES DELIVERY SERVICES TO YOU. YOU UNDERSTAND THAT BY USING THE SERVICE, YOUR ITEMS MAY BE EXPOSED TO SITUATIONS THAT ARE POTENTIALLY DANGEROUS OR HARMFUL, UNSAFE OR OTHERWISE OBJECTIONABLE, AND THAT YOU USE THE SERVICE AT YOUR OWN RISK.
  13. Notice
  Fast Foodie may give notice by any means of communication reasonably anticipated to notify you of the information provided. By way of example only, such communication may be a general notice on the Service or via email to the email address listed on your Fast Foodie account. It is your obligation to update your account information so that we may contact you as may be necessary. Such notice shall be deemed to have been given 48 hours after dispatch. If physical notice (e.g., US Mail) is used, then such notice shall be deemed to have been given 7 days after dispatch.
  You may give notice to Fast Foodie (such notice shall be deemed given when received by Fast Foodie) at any time by any of the following: letter delivered by nationally recognized overnight delivery service or first class postage prepaid mail to Fast Foodie at the following address:
  Melanite LLC
  Fast Foodie
  1755 North Brown Road
  Suite 200
  Lawrenceville, GA 30043




  14. Assignment
  You may not assign or transfer these Terms or your rights under these Terms, in whole or in part, by operation of law or otherwise, without our prior written consent. We may assign these Terms in whole or in part at any time to any entity without your notice or consent. Any purported assignment by you in violation of this section shall be void.
  15. Term and Termination of Agreement
  These Terms are effective until terminated by you or Fast Foodie as described below. Your rights under these Terms will terminate automatically without notice from Fast Foodie if you fail to comply with any of these Terms (including by violating any license restriction contained in these Terms). In addition, Fast Foodie may in its sole discretion terminate your user account on the Service or suspend or terminate your access to the Service at any time without notice. We also reserve the right to modify or discontinue the Service at any time (including by limiting or discontinuing certain features of the Service) without notice to you. We will have no liability whatsoever on account of any change to the Service or any suspension or termination of your access to or use of the Service. You may terminate these Terms at any time by closing your account, uninstalling the App, and ceasing use of the Service.
  16. Dispute Resolution and Arbitration
  16.A - Disputes
  Fast Foodie is not a party to, has no involvement or interest in, makes no representations or warranties as to, and has no responsibility or liability with respect to any communications, transactions, interactions, disputes or any relations whatsoever between you and any other user, any Courier or other third party. Disputes between a user and Fast Foodie are subject to this in Section 16.
  16.B - Widespread
  In the interest of resolving disputes between you and Fast Foodie in the most expedient and cost effective manner, you and Fast Foodie agree that every dispute arising in connection with these Terms will be resolved by binding arbitration. Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, may allow for more limited discovery than in court, and can be subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. Our agreement to arbitrate disputes includes all claims arising out of or relating to any aspect of these Terms, whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and regardless of whether a claim arises during or after the termination of these Terms.
  YOU UNDERSTAND AND AGREE THAT, BY ENTERING INTO THESE TERMS, YOU AND POSTMATES ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION.
  16.C - Anomaly
  Despite the provisions of the paragraph directly above, we both agree that nothing in these Terms will be deemed to waive, preclude, or otherwise limit the right of either of us to:
  Bring an individual action in small claims court;
  Pursue an enforcement action through the applicable federal, state, or local agency if that action is available;
  Seek injunctive relief in a court of law; or
  To file suit in a court of law to address an intellectual property infringement claim.
  16.D - Arbitrator
  Any arbitration between you and Fast Foodie will be governed by the Commercial Dispute Resolution Procedures and the Supplementary Procedures for Consumer Related Disputes (collectively, "AAA Rules") of the American Arbitration Association ("AAA"), as modified by these Terms, and will be administered by the AAA. The AAA Rules and filing forms are available online at www.adr.org, or by calling the AAA at 1-800-778-7879
  16.E – Notice Process
  A party who intends to seek arbitration must first send a written notice of the dispute to the other, by certified mail or Federal Express (signature required), or if we do not have a physical address on file for you, by electronic mail ("Notice").
  Fast Foodie’ address for Notice is:
  Melanite LLC
  Fast Foodie
  1755 North Brown Road
  Suite 200
  (678) 690-5339
  The Notice must:
  Describe the nature and basis of the claim or dispute; and
  Set forth the specific relief sought ("Demand")
  We agree to use good faith efforts to resolve the claim directly, but if we do not reach an agreement to do so within 30 days after the Notice is received, you or Fast Foodie may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by you or Fast Foodie must not be disclosed to the arbitrator until after the arbitrator makes a final decision and award, if any.
  If our dispute is finally resolved through arbitration in your favor, Fast Foodie will pay you the highest of the following:
  The amount awarded by the arbitrator, if any;
  The last written settlement amount offered by Fast Foodie in settlement of the dispute prior to the arbitrator’s award; or
  $1,000
  16.F - Fees
  If you commence arbitration in accordance with these Terms, Fast Foodie will reimburse you for your payment of the filing fee, unless your claim is for more than $10,000, in which case the payment of any fees will be decided by the AAA Rules.
  Any arbitration hearing will take place at a location to be agreed upon in Gwinnett County, Georgia, but if the claim is for $10,000 or less, you may choose whether the arbitration will be conducted:
  Solely on the basis of documents submitted to the arbitrator;
  Through a non-appearance based telephone hearing; or
  By an in-person hearing as established by the AAA Rules in the county (or parish) of your billing address
  If the arbitrator finds that either the substance of your claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all fees will be governed by the AAA Rules. In that case, you agree to reimburse Fast Foodie for all monies previously disbursed by it that are otherwise your obligation to pay under the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator must issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based.
  The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees or expenses at any time during the proceeding and upon request from either party made within 14 days of the arbitrator’s ruling on the merits.
  16.G – No Class Actions
  YOU AND FAST FOODIE AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.
  Further, unless both you and Fast Foodie agree otherwise, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding.
  16.H - Modifications
  If Fast Foodie makes any future change to this arbitration provision (other than a change to Fast Foodie’ address for Notice), you may reject the change by sending us written notice within 30 days of the change to Fast Foodie’ address for Notice, in which case your account with Fast Foodie will be immediately terminated and this arbitration provision, as in effect immediately prior to the amendments you reject, will survive.
  16.I - Enforceability
  If Section 16.G is found to be unenforceable or if the entirety of this Section 16 is found to be unenforceable, then the entirety of this Section 16 will be null and void and, in that case.
  17. Modification Of These Terms
  We reserve the right to update or modify the Terms at any time without prior notice, and such changes will be effective immediately upon being posted through the Service, except as set forth below. These Terms identify the date of last update. Your use of the Service following any such change constitutes your agreement to be bound by the modified Terms of Service. In the case of material changes to these Terms, we will make reasonable efforts to notify you of the change, such as through sending an email to any address you may have used to register for an account, through a pop-up window on the Service, or other similar mechanism.
  Material changes to these Terms will be effective upon the earlier of:
  Your first use of the Service with actual notice of such change, or
  30 days from posting of such change.
  Disputes arising under these Terms will be resolved in accordance with the version of the Terms in place at the time the dispute arose. We encourage you to review these Terms frequently to stay informed of the latest modifications.
  18. General
  If a lawsuit or court proceeding is permitted under these Terms, you and Fast Foodie agree to submit to the personal and exclusive jurisdiction of the state courts and federal courts located within Gwinnett County, Georgia for the purpose of litigating any dispute. We operate the Service from our offices in Georgia, and we make no representation that materials included in the Service are appropriate or available for use in other locations. No joint venture, partnership, employment, or agency relationship exists between you, Fast Foodie or any third-party provider as a result of the Terms or use of the Service.
  If any provision of the Agreement is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law. The failure of Fast Foodie to enforce any right or provision in this Agreement shall not constitute a waiver of such right or provision unless acknowledged and agreed to by Fast Foodie in writing.
  This Agreement comprises the entire agreement between you and Fast Foodie and supersedes all prior or contemporaneous negotiations, discussions or agreements, whether written or oral, between the parties regarding the subject matter contained in these Terms.
  19. Notice Regarding Apple
  To the extent that you are using our mobile applications on an iOS device, you further acknowledge and agree to the terms of this Section 19. You acknowledge that these Terms are between you and Fast Foodie only, not with Apple Inc. ("Apple"), and Apple is not responsible for the Service and the content thereof.
  Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the Service. In the event of any failure of the Service to conform to any applicable warranty, you may notify Apple and Apple will refund any applicable purchase price for the mobile application to you; and, to the maximum extent permitted by applicable law, Apple has no other warranty obligation whatsoever with respect to the Service.
  Apple is not responsible for addressing any claims by you or any third party relating to the Service or your possession and/or use of the Service, including, but not limited to:
  Product liability claims;
  Any claim that the Service fails to conform to any applicable legal or regulatory requirement; and
  Claims arising under consumer protection or similar legislation
  Apple is not responsible for the investigation, defense, settlement and discharge of any third-party claim that the Service and/or your possession and use of the mobile application infringes that third party’s intellectual property rights. You agree to comply with any applicable third-party terms when using the Service. Apple and Apple’s subsidiaries are third-party beneficiaries of these Terms, and upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third-party beneficiary of these Terms.
  You hereby represent and warrant that:
  You are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a "terrorist supporting" country; and
  You are not listed on any U.S. Government list of prohibited or restricted parties.
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
